name: kotlin-native-basics Pull Request

on:
  push:
    branches:
      - '!main'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v5
        - name: Set up JDK 21
          uses: actions/setup-java@v5
          with:
            java-version: '21'
            distribution: 'adopt'
        - name: Set up gradle
          uses: gradle/actions/setup-gradle@v3

        - name: Install
          run: make install

        - name: Build and Test
          run:  make build-pipeline
